image: node:latest

stages: 
  - build
  - production

cache:
  paths:
    - node_modules/

install-dependencies:
  stage: build
  script: 
    - npm install
  artifacts:
    paths:
      - node_modules/

production:
  type: deploy
  stage: production
  script:
    - npm install --production
    - (echo "machine git.heroku.com"; echo " login vishnuduveys@gmail.com"; echo " password $HEROKU_API_KEY") > ~/.netrc
    - git push https://git.heroku.com/appbuynsell.git
  only:
    - master