--- 
cache: 
  paths: 
    - node_modules/
image: "node:latest"
install-dependencies: 
  artifacts: 
    paths: 
      - node_modules/
  script: 
    - "npm install"
  stage: build
lint-checks: 
  script: 
    - "npm run lint"
  stage: test
production: 
  only: 
    - master
  script: 
    - "npm install --production"
    - "(echo \"machine git.heroku.com\"; echo \" login vishnuduveys@gmail.com\"; echo \" password $HEROKU_API_KEY\") > ~/.netrc"
    - "git push https://git.heroku.com/appbuynsell.git HEAD:master"
  stage: production
  type: deploy
stages: 
  - build
  - production